package com.unisys.br.amsfw.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated
 * source version: 2.1
 * 
 */
@WebService(name = "ProcessamentoWS", targetNamespace = "http://processamento.ws.amsfw.br.unisys.com/")
@XmlSeeAlso({ObjectFactory.class })
public interface ProcessamentoWS {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "executarProcessamento",
			targetNamespace = "http://processamento.ws.amsfw.br.unisys.com/",
			className = "com.unisys.br.amsfw.ws.processamento.ExecutarProcessamento")
	@ResponseWrapper(localName = "executarProcessamentoResponse",
			targetNamespace = "http://processamento.ws.amsfw.br.unisys.com/",
			className = "com.unisys.br.amsfw.ws.processamento.ExecutarProcessamentoResponse")
	void executarProcessamento(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
