package com.unisys.br.amsfw.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessamentoWSService", targetNamespace = "http://processamento.ws.amsfw.br.unisys.com/",
		wsdlLocation = "http://localhost:8080/amsfw-ws-1.0.0-SNAPSHOT/ProcessamentoWS?wsdl")
public class ProcessamentoWSService extends Service {

	private static final URL PROCESSAMENTOWSSERVICE_WSDL_LOCATION;
	private static final Logger LOGGER = Logger.getLogger(com.unisys.br.amsfw.client.ws.ProcessamentoWSService.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.unisys.br.amsfw.client.ws.ProcessamentoWSService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/amsfw-ws-1.0.0-SNAPSHOT/ProcessamentoWS?wsdl");
		} catch (MalformedURLException e) {
			LOGGER.warning("Failed to create URL for the wsdl Location: "
					+ "'http://localhost:8080/amsfw-ws-1.0.0-SNAPSHOT/ProcessamentoWS?wsdl', retrying as a local file");
			LOGGER.warning(e.getMessage());
		}
		PROCESSAMENTOWSSERVICE_WSDL_LOCATION = url;
	}

	/**
	 * Construtor de ProcessamentoWSService.
	 * 
	 * @param wsdlLocation
	 * @param serviceName
	 */
	public ProcessamentoWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/**
	 * Construtor de ProcessamentoWSService.
	 * 
	 */
	public ProcessamentoWSService() {
		super(PROCESSAMENTOWSSERVICE_WSDL_LOCATION, new QName(
				"http://processamento.ws.amsfw.br.unisys.com/",
				"ProcessamentoWSService"));
	}

	/**
	 * 
	 * @return returns ProcessamentoWS
	 */
	@WebEndpoint(name = "ProcessamentoWSPort")
	public ProcessamentoWS getProcessamentoWSPort() {
		return super.getPort(new QName("http://processamento.ws.amsfw.br.unisys.com/", "ProcessamentoWSPort"),
				ProcessamentoWS.class);
	}

	/**
	 * 
	 * @return returns ProcessamentoWS
	 */
	@WebEndpoint(name = "ProcessamentoWSPort")
	public ProcessamentoWS getProcessamentoWSPort(String port) {
		return super.getPort(new QName("http://processamento.ws.amsfw.br.unisys.com/", port), ProcessamentoWS.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ProcessamentoWS
	 */
	@WebEndpoint(name = "ProcessamentoWSPort")
	public ProcessamentoWS getProcessamentoWSPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://processamento.ws.amsfw.br.unisys.com/", "ProcessamentoWSPort"),
				ProcessamentoWS.class, features);
	}

}
